import { describe, it, expect, vi } from 'vitest';
import { standardPull } from './standard-pull.js';
import { ayakaPart } from './ayaka-part.js';
function context(){const elements=new Map();const ctx={state:{cz:null},$:id=>{if(!elements.has(id))elements.set(id,{style:{}});return elements.get(id)},check:()=>{},tween:vi.fn(async(ms,fn)=>fn(1)),anim:vi.fn(async()=>{}),animateRaw:vi.fn(),wait:vi.fn(async()=>{}),caption:vi.fn(),sfx:vi.fn(),playPull:vi.fn(),stopSfx:vi.fn(),spawn:vi.fn(),makeCracks:vi.fn(),W:1440,H:900,DPR:1,fadePull:vi.fn(),playTheme:vi.fn(),snow:vi.fn(),voice:vi.fn(async()=>{}),THEME:{pause:vi.fn(),play:vi.fn(async()=>{})},rampTheme:vi.fn()};return ctx}
describe('approved reveal sequence',()=>{
 it('keeps Seren premium tell gold, plays the S+ cue, and hands off after shatter',async()=>{const ctx=context();ctx.stopBeforeSilhouette=true;ctx.premiumTell=true;await standardPull(ctx,'S+');expect(ctx.sfx.mock.calls.map(c=>c[0])).toEqual(['pull_fall_whoosh','tell_splus','pull_flash_swell']);expect(ctx.tween.mock.calls.map(c=>c[0])).toEqual([1500,900,900,1000]);expect(ctx.makeCracks).not.toHaveBeenCalled();expect(ctx.state.cz).toMatchObject({stage:1,show:false});});
 it('hands off after shatter to the approved character silhouette without clearing the crystal state early',async()=>{const ctx=context();ctx.stopBeforeSilhouette=true;await standardPull(ctx,'S++');expect(ctx.state.cz).toMatchObject({show:false,stage:2});expect(ctx.state.cracks).toEqual([]);expect(ctx.wait).not.toHaveBeenCalled();expect(ctx.anim).toHaveBeenCalledTimes(3)});
 it.each(['A','S+','S++'])('shares the pull and stops at the proper %s tell',async grade=>{const ctx=context();await standardPull(ctx,grade);expect(ctx.playPull).toHaveBeenCalledOnce();expect(ctx.tween.mock.calls.map(c=>c[0])).toEqual(grade==='A'?[1500]:grade==='S+'?[1500,900]:[1500,900,900,1200]);expect(ctx.makeCracks).toHaveBeenCalledTimes(grade==='S++'?1:0);expect(ctx.spawn.mock.calls[0][0]).toBe(140);expect(ctx.state.cz).toBeNull()});
 it('waits for each voice and holds the paused Waltz through the freeze',async()=>{const ctx=context();let finishReveal,finishChrono,finishAfter,finishFreeze;ctx.voice.mockImplementation(id=>new Promise(resolve=>{if(id==='voReveal')finishReveal=resolve;else if(id==='voChrono')finishChrono=resolve;else finishAfter=resolve}));ctx.wait.mockImplementation(ms=>ms===1800?new Promise(resolve=>finishFreeze=resolve):Promise.resolve());const run=ayakaPart(ctx);await vi.waitFor(()=>expect(finishReveal).toBeTypeOf('function'));expect(ctx.voice.mock.calls).toEqual([['voReveal']]);expect(ctx.THEME.pause).not.toHaveBeenCalled();finishReveal();await vi.waitFor(()=>expect(finishChrono).toBeTypeOf('function'));expect(ctx.THEME.pause).not.toHaveBeenCalled();finishChrono();await vi.waitFor(()=>expect(finishFreeze).toBeTypeOf('function'));expect(ctx.state.frozen).toBe(true);expect(ctx.THEME.pause).toHaveBeenCalledOnce();expect(ctx.THEME.play).not.toHaveBeenCalled();finishFreeze();await vi.waitFor(()=>expect(finishAfter).toBeTypeOf('function'));expect(ctx.state.frozen).toBe(false);expect(ctx.THEME.play).toHaveBeenCalledOnce();expect(ctx.rampTheme).not.toHaveBeenCalled();finishAfter();await run;expect(ctx.rampTheme).toHaveBeenCalledWith(.55)});
 it('does not continue the pull after cancellation',async()=>{const ctx=context();ctx.check=()=>{throw new DOMException('Canceled','AbortError')};await expect(standardPull(ctx,'S++')).rejects.toMatchObject({name:'AbortError'});expect(ctx.makeCracks).not.toHaveBeenCalled();expect(ctx.spawn).not.toHaveBeenCalled()});
});
