export type Grade = 'S++' | 'S+' | 'A';
export interface Character {
  id: string; name: string; title: string; grade: Grade; element: string; accent: string;
  description: string; splash?: string; cutout?: string;
  splashLabel?: string; extraArt?: { label: string; src: string }[];
  forms?: { label: string; cutout: string; background: string }[];
}
const art = (id: string, name: string) => `${import.meta.env.BASE_URL}art/${id}/${name}.webp`;
export const WORLD = `${import.meta.env.BASE_URL}art/lumara-world-v1.webp`;
export const characters: Character[] = [
  { id: 'seren', name: 'Seren', title: 'Dawnlight', grade: 'S+', element: 'Light', accent: '#795b30', description: 'Your guide to Lumara. Silver hair, a crystal sword, and the promise of another dawn. Where the last light fades, she is the first to welcome you home.', splash: art('seren','seren_splash_v3'), cutout: art('seren','seren_cutout_v2'), splashLabel: 'Dawnlight', extraArt: [{ label: 'Arrival in Aurelis', src: art('seren','seren_arrival') }, { label: 'Dawnbreak', src: art('seren','seren_dawnbreak') }] },
  { id: 'mahesvara', name: 'Mahesvara', title: 'Beyond the veil', grade: 'S++', element: 'Void', accent: '#436e97', description: 'A calm, ruthless genius wielding twin crystal guns. In his awakened form, glass wings reveal a power that can both destroy and restore.', splash: art('mahesvara','mahesvara_mirror_splash_v2'), cutout: art('mahesvara','mahesvara_cutout'), splashLabel: 'Mirrored forms', extraArt: [{ label: 'Cinematic landscape', src: `${import.meta.env.BASE_URL}art/landscapes/mahesvara.webp` }, { label: 'Awakened form', src: art('mahesvara','mahesvara_awakened_splash_v2') }], forms: [{ label: 'Original form', cutout: art('mahesvara','mahesvara_cutout'), background: art('mahesvara','mahesvara_mirror_splash_v2') }, { label: 'Awakened form', cutout: art('mahesvara','mahesvara_awakened_cutout'), background: art('mahesvara','mahesvara_awakened_splash_v2') }] },
  { id: 'keira', name: 'Keira', title: 'A spark in the system', grade: 'S++', element: 'Flame', accent: '#a04574', description: 'A playful digital ghost with a pink flame sword and a towering mech guardian. Even a world of forgotten promises has room for a little mischief.', splash: art('keira','keira_splash_v3'), cutout: art('keira','keira_cutout'), splashLabel: 'Floating pose', extraArt: [{ label: 'Cinematic landscape', src: `${import.meta.env.BASE_URL}art/landscapes/keira.webp` }, { label: 'Standing pose', src: art('keira','keira_splash_v2') }], forms: [{ label: 'Standing pose', cutout: art('keira','keira_cutout'), background: art('keira','keira_splash_v2') }, { label: 'Floating pose', cutout: art('keira','keira_cutout_floating'), background: art('keira','keira_splash_v3') }] },
  { id: 'ayaka', name: 'Ayaka', title: 'A moment outside time', grade: 'S++', element: 'Ice / Time', accent: '#476b86', description: 'An effortless ice-magic prodigy with a secret love of doing absolutely nothing. She can slow time—or stop it entirely. Just enough time for another nap.', splash: art('ayaka','ayaka_timestop_splash_v2'), cutout: art('ayaka','ayaka_cutout'), splashLabel: 'Time stop', extraArt: [{ label: 'Ice throne', src: art('ayaka','ayaka_splash_v1') }, { label: 'Cinematic landscape', src: `${import.meta.env.BASE_URL}art/landscapes/ayaka.webp` }], forms: [{ label: 'Ice throne', cutout: art('ayaka','ayaka_cutout'), background: art('ayaka','ayaka_splash_v1') }, { label: 'Time stop', cutout: art('ayaka','ayaka_cutout_timestop'), background: art('ayaka','ayaka_timestop_splash_v2') }] },
  { id: 'azrenth', name: 'Azrenth', title: 'Crowned in black flame', grade: 'S++', element: 'Destruction', accent: '#914f53', description: 'A reincarnated demon king with destruction in his eyes and a crown of black flame. Arrogant calm hides behind the guise of an ordinary student.', splash: art('azrenth','azrenth_splash_v2'), cutout: art('azrenth','azrenth_cutout'), splashLabel: 'World in his hand', extraArt: [{ label: 'Severed world', src: `${import.meta.env.BASE_URL}art/landscapes/azrenth.webp` }, { label: 'Venuzdonoa', src: art('azrenth','azrenth_venuzdonoa') }] },
  { id: 'lucien', name: 'Lucien Valmaire', title: 'The Great Moon', grade: 'S+', element: 'Moonlit Lightning', accent: '#6f63b8', description: "A weary young count everyone calls a mastermind. His chants bind a forgotten god's vow, and a hundred bolts of lightning answer.", splash: art('lucien','lucien_splash_v1'), cutout: art('lucien','lucien_cutout'), splashLabel: 'The Great Moon', extraArt: [{ label: 'Moonlit chant', src: art('lucien','lucien_chant') }, { label: 'Hundredfold Chain', src: art('lucien','lucien_hundredfold_chain') }] },
  { id: 'ashvane', name: 'Ashvane', title: 'The quiet vanguard', grade: 'S+', element: 'Earth / Battle', accent: '#896140', description: 'A retired battle mage with a dry wit and a talent for finding somewhere to nap. When he lifts his spear, the legend returns in a flawless rush of strikes.', splash: art('ashvane','ashvane_splash_v2'), cutout: art('ashvane','ashvane_cutout_v2') },
  { id: 'suvara', name: 'Suvara', title: 'Keeper of the horizon', grade: 'S+', element: 'Radiant light', accent: '#327373', description: 'A young ruler seated upon her guardian light dragon. Dutiful and composed, she carries a broadsword and the weight of tomorrow upon her shoulders.', splash: art('suvara','suvara_splash_v3'), cutout: art('suvara','suvara_cutout_v2') },
  { id: 'sollene', name: 'Sollene', title: 'Moonlit devotion', grade: 'A', element: 'Moonlight', accent: '#5c5e86', description: 'A gentle moon priestess with a crescent staff and a wide-brimmed hat. In a quiet cathedral garden, she kneels in prayer beneath the moonlight.', splash: art('sollene','sollene_splash_v1'), cutout: art('sollene','sollene_cutout') },
  { id: 'wren', name: 'Wren', title: 'On the wind', grade: 'A', element: 'Wind', accent: '#316956', description: 'A small, energetic archer with jade-green hair and a grin that never quite goes away. Glowing green arrows follow her through every impossible leap.', splash: art('wren','wren_splash_v1'), cutout: art('wren','wren_cutout') },
  { id: 'rook', name: 'Rook', title: 'Lightning on the rooftops', grade: 'A', element: 'Lightning', accent: '#846432', description: 'A laid-back bounty hunter in a charcoal duster. An amber streak, a cheek scar, and a lightning revolver make this gunslinger hard to forget.', splash: art('rook','rook_splash_v1'), cutout: art('rook','rook_cutout') },
  { id: 'calla', name: 'Calla', title: 'A curious concoction', grade: 'A', element: 'Poison', accent: '#46715c', description: 'A sly alchemist with violet hair, a monocle, and an emerald flask. Her coat is lined with vials; what is inside them is another question entirely.', splash: art('calla','calla_splash_v1'), cutout: art('calla','calla_cutout') },
  { id: 'kairo', name: 'Kairo', title: 'Still waters', grade: 'A', element: 'Water', accent: '#316b68', splash: art('kairo','kairo_splash_v1'), description: 'A quiet wandering swordsman with sea-green hair and a coral-hilted katana. Wave embroidery runs along his coat, echoing the shore he calls home.', cutout: art('kairo','kairo_cutout') },
  { id: 'dax', name: 'Dax', title: 'Fire in his fists', grade: 'A', element: 'Fire', accent: '#9a542f', description: 'A hot-headed brawler with spiky orange hair and blazing fists. Wrapped arms and a flame-patterned jacket are all he needs to step into the arena.', splash: art('dax','dax_splash_v1'), cutout: art('dax','dax_cutout') },
];
