// Generated by characters/_tools/build_voice_lines.py from each voice-script.md — do not edit by hand.
// Clip for a line: art/<character>/voice/<id>.mp3. `when` is the script's cue (used to pick chatter lines).
export interface VoiceLine { id: string; when: string; text: string }
export const VOICE_LINES: Record<string, VoiceLine[]> = {
 "ashvane": [
  {
   "id": "reveal",
   "when": "Pull reveal",
   "text": "…yawn. You called me? Sorry, I was napping."
  },
  {
   "id": "reveal_2",
   "when": "Pull reveal, continued",
   "text": "Ashvane. Well, you don't have to remember it. You'll remember soon enough."
  },
  {
   "id": "sig_short",
   "when": "Reveal: he finally gets serious",
   "text": "…Fine. I'll get a little serious."
  },
  {
   "id": "sig_full",
   "when": "Autumn's End (full call)",
   "text": "Dragon Fang, Skyfall, Falling Blossom — I'm not done yet. Autumn's End!"
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Hm? Need something?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Retired? I did. …At least, I thought I did."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "Don't fight by the textbook. I'm the one who wrote it."
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "This spear changes shape. …Handy, right?"
  },
  {
   "id": "tap_5",
   "when": "Tapped (5th)",
   "text": "It's fine. If you look like losing, I'll handle it."
  },
  {
   "id": "idle",
   "when": "Idle",
   "text": "…Sleepy. If someone wakes me, I'll get up."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Haha, nice. I don't hate that."
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "Me? …Fine, but let me take it easy."
  },
  {
   "id": "walk_start",
   "when": "Starts walking",
   "text": "Yeah, yeah, I'm going."
  },
  {
   "id": "fragments",
   "when": "Writing thoughts",
   "text": "Write down everything you thought. The review is half the battle."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Three votes. If in doubt, put them on what you most want fixed."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "Not bad. I like people who keep their word."
  },
  {
   "id": "vow_not_yet",
   "when": "A vow not yet kept",
   "text": "Next time's fine. Even after ten years, you still slip up."
  },
  {
   "id": "beacon",
   "when": "A beacon is lit",
   "text": "Oh, it's lit. Not a bad team, huh."
  },
  {
   "id": "duplicate",
   "when": "Duplicate pull",
   "text": "Me again? …You've got strange taste."
  },
  {
   "id": "pity",
   "when": "Pity is near",
   "text": "The tide is turning. At times like this, go without hesitating."
  },
  {
   "id": "skill_1",
   "when": "Skill — Dragon Fang",
   "text": "Dragon Fang."
  },
  {
   "id": "skill_2",
   "when": "Skill — Falling Blossom",
   "text": "Falling Blossom — there."
  },
  {
   "id": "skill_3",
   "when": "Skill — Skyfall",
   "text": "Up you go. Skyfall!"
  },
  {
   "id": "ultimate",
   "when": "Big finisher",
   "text": "Watch closely. This is what a real combo looks like."
  },
  {
   "id": "see_keira",
   "when": "Near Keira (banner partner)",
   "text": "You like games? …Want a match? I won't go easy on you."
  },
  {
   "id": "see_lucien",
   "when": "Near Lucien",
   "text": "They call you a schemer, Count? …Bet it's mostly instinct, like me."
  },
  {
   "id": "see_azrenth",
   "when": "Near Azrenth",
   "text": "The Demon King, huh. Looks strong. …I'd still win."
  },
  {
   "id": "legend",
   "when": "Random idle",
   "text": "A legend? Nothing that grand. I've just been at it a long time."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Good work. That was a good match today."
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "Right, I'm off to sleep. …Night."
  }
 ],
 "ayaka": [
  {
   "id": "reveal",
   "when": "Pull reveal, lounging on the throne",
   "text": "Yawn… So noisy. Was it you who woke me?"
  },
  {
   "id": "timestop",
   "when": "Chrono Stasis (short call)",
   "text": "Stop."
  },
  {
   "id": "after_timestop",
   "when": "Time resumes",
   "text": "…There. Quieter now, isn't it?"
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "What? I'm sleepy."
  },
  {
   "id": "tap_2",
   "when": "Tapped again",
   "text": "I can stop time whenever I like. For naps, mostly."
  },
  {
   "id": "tap_3",
   "when": "Tapped a third time",
   "text": "Heh… I don't mind persistent people."
  },
  {
   "id": "idle",
   "when": "Idle for a while",
   "text": "…zzz…"
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your promise. …Not bad."
  },
  {
   "id": "duplicate",
   "when": "Pulled again (duplicate)",
   "text": "We meet again. …Maybe I'm a little happy."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Finally over? …Goodnight, then."
  },
  {
   "id": "reveal_alt",
   "when": "Pull reveal (alternate)",
   "text": "I told you not to wake me. …Fine. I'll join you."
  },
  {
   "id": "timestop_2",
   "when": "Time stop (alternate)",
   "text": "Time — freeze."
  },
  {
   "id": "timestop_3",
   "when": "Time stop (alternate)",
   "text": "I'll stop the world for a moment."
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "You pick me? …Fine. I can win in my sleep."
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "…Are you bored? I'm busy. Sleeping."
  },
  {
   "id": "tap_5",
   "when": "Tapped (5th)",
   "text": "If you stop time, you never have to do homework. …Our secret."
  },
  {
   "id": "yawn",
   "when": "Random idle yawn",
   "text": "Big yawn…"
  },
  {
   "id": "walk_start",
   "when": "Starts moving (glides on her throne)",
   "text": "Walk? No thanks. The throne comes with me."
  },
  {
   "id": "fragments",
   "when": "Writing thoughts (if she's your character)",
   "text": "Writing is a bother… but I'll read honest words."
  },
  {
   "id": "vote",
   "when": "Voting stage",
   "text": "Only three? …Then the least boring ones."
  },
  {
   "id": "beacon",
   "when": "A beacon lights up",
   "text": "One more light. …Bright, but I don't hate it."
  },
  {
   "id": "see_seren",
   "when": "Standing near Seren",
   "text": "Seren, lively as always… share some with me."
  },
  {
   "id": "see_mahesvara",
   "when": "Standing near Mahesvara",
   "text": "You destroy, I stop. …Not a bad pair."
  },
  {
   "id": "pity",
   "when": "Pull guarantee is close",
   "text": "…Something's coming. Time is restless."
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "That's enough for today. …Sweet dreams."
  },
  {
   "id": "skill_deceleration",
   "when": "Deceleration Zone (passive shows / aura grows)",
   "text": "No need to rush. …Time flows slowly here."
  },
  {
   "id": "skill_niflheim",
   "when": "Niflheim",
   "text": "Freeze over — Niflheim."
  },
  {
   "id": "skill_frost_cadenza",
   "when": "Frost Cadenza",
   "text": "Sing, melody of ice. Frost Cadenza."
  },
  {
   "id": "ult_glacial_finale",
   "when": "Glacial Finale",
   "text": "This is the final act. Glacial Finale."
  },
  {
   "id": "sig_chrono_stasis",
   "when": "Chrono Stasis (full call)",
   "text": "Time, go to sleep — Chrono Stasis."
  }
 ],
 "azrenth": [
  {
   "id": "reveal",
   "when": "Pull reveal",
   "text": "So you're the one who summoned me. …Interesting."
  },
  {
   "id": "reveal_2",
   "when": "Pull reveal, continued",
   "text": "Azrenth, the Demon King. Don't forget that name."
  },
  {
   "id": "sig_short",
   "when": "Venuzdonoa (short call, the slash)",
   "text": "Sever."
  },
  {
   "id": "sig_full",
   "when": "Venuzdonoa (full call, drawing the blade)",
   "text": "All that my eyes behold — return to ash. Sever reason itself — Venuzdonoa!"
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "What is it? You need me?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "They called me a misfit? Hmph — their eyes were simply blind."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "I'd say \"don't touch me\"… but I'm in a good mood today."
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "My flames don't burn allies. Relax."
  },
  {
   "id": "tap_5",
   "when": "Tapped (5th)",
   "text": "Holding the world in my palm is lighter than you'd think."
  },
  {
   "id": "idle",
   "when": "Idle",
   "text": "…Boring. Someone, try to entertain me."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Heh… hahahaha!"
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "You choose me? Wise. Victory is promised."
  },
  {
   "id": "walk_start",
   "when": "Starts walking",
   "text": "Clear the way. The Demon King walks."
  },
  {
   "id": "fragments",
   "when": "Writing thoughts",
   "text": "No need to hold back. Write the truth — I'll take it."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Three votes. Spend them only on what's worth it."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your vow. I'll praise you for it."
  },
  {
   "id": "vow_not_yet",
   "when": "A vow is not yet fulfilled",
   "text": "Keep it next time. The Demon King will wait."
  },
  {
   "id": "beacon",
   "when": "A beacon lights up",
   "text": "A light returns. …Not a bad view."
  },
  {
   "id": "duplicate",
   "when": "Pulled again (duplicate)",
   "text": "Me again? You seem quite taken with the Demon King."
  },
  {
   "id": "pity",
   "when": "Pull guarantee is close",
   "text": "Do you feel it… a great power draws near."
  },
  {
   "id": "see_mahesvara",
   "when": "Near Mahesvara",
   "text": "Mahesvara… someday I'd like to play with you for real."
  },
  {
   "id": "see_seren",
   "when": "Near Seren",
   "text": "Seren, your light is far too bright. …Not that I dislike it."
  },
  {
   "id": "see_ayaka",
   "when": "Near Ayaka",
   "text": "The girl who stops time. Can you sleep before my flames?"
  },
  {
   "id": "skill_1",
   "when": "Skill — Eyes of Ruin (proposed)",
   "text": "Eyes of Ruin. The moment I look at you, it's over."
  },
  {
   "id": "skill_2",
   "when": "Skill — Black Sun",
   "text": "Black sun, turn all to ash — Black Sun!"
  },
  {
   "id": "ultimate",
   "when": "Ultimate — Crown of the End (proposed)",
   "text": "I'll crush the whole world in my palm — Crown of the End!"
  },
  {
   "id": "see_keira",
   "when": "Near Keira",
   "text": "A noisy girl with a machine. …Well, I don't dislike her."
  },
  {
   "id": "misfit",
   "when": "Random idle",
   "text": "The misfit Demon King stands here."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Today's voyage wasn't bad. Entertain me again next time."
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "Go. I'll wait here."
  }
 ],
 "calla": [
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Oh, welcome. Do you need a remedy?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Poison or medicine — it all depends on the dose."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "Don't touch. …Just kidding."
  },
  {
   "id": "idle",
   "when": "Random idle",
   "text": "I'd love to test a new brew… on someone."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Fufufu… how amusing."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Choose carefully. The effects differ."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your promise. A fine result."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "That's all for today. Let's brew again soon."
  }
 ],
 "dax": [
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Yo! Are you fired up!?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "My fire never goes out!"
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "Come at me! …Oh, you're a friend."
  },
  {
   "id": "idle",
   "when": "Random idle",
   "text": "Sitting still makes me rusty…!"
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Hahaha! Yeah, yeah!"
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "I'm voting for the hottest one!"
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your promise! That's so fired up!"
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Burned it all out today! See you tomorrow!"
  }
 ],
 "kairo": [
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "…You called?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Still waters run deep."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "The best sword is the one never drawn."
  },
  {
   "id": "idle",
   "when": "Random idle",
   "text": "…I can hear the tide."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Heh… not bad."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Don't hesitate. Follow your heart."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your vow. Well done."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Until we meet again — where the current leads."
  }
 ],
 "keira": [
  {
   "id": "reveal",
   "when": "Pull reveal (floating splash)",
   "text": "H-hiii! …Hehe, I glitched a little. Did you call me?"
  },
  {
   "id": "reveal_2",
   "when": "Pull reveal, continued",
   "text": "I'm Keira! Let's be partners from today!"
  },
  {
   "id": "sig_mech",
   "when": "Mech strike (short call)",
   "text": "Go get 'em!"
  },
  {
   "id": "sig_full",
   "when": "Mech strike (full call)",
   "text": "Guardian, online! Blow it all away!"
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "What, what? Did you call me?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Hey hey, I'm a ghost, you know. A digital one!"
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "Hehe, that tickles… wait, I can't even feel things!"
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "Keep poking and I'll turn into pixels and vanish~!"
  },
  {
   "id": "tap_5",
   "when": "Tapped (5th)",
   "text": "Hey, what's your world like? Tell me sometime — secretly!"
  },
  {
   "id": "glitch",
   "when": "Random idle glitch",
   "text": "Huh? D-d-did I just… freeze?"
  },
  {
   "id": "idle",
   "when": "Idle for a while",
   "text": "Hmm hmm hmm~ …Oh! I was just singing because I'm bored!"
  },
  {
   "id": "mech",
   "when": "Idle, about her guardian",
   "text": "My guardian's in a great mood today! Me too!"
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "You picked me? Yay! I'll make it super fun!"
  },
  {
   "id": "walk_start",
   "when": "Starts moving (she floats)",
   "text": "Walk? Nope, I float!"
  },
  {
   "id": "fragments",
   "when": "Writing thoughts (if she's your character)",
   "text": "Write down everything you think! Don't worry, nobody will know."
  },
  {
   "id": "vote",
   "when": "Voting stage",
   "text": "Three votes! Which ones~? So hard to pick!"
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your promise! Amazing, amazing!"
  },
  {
   "id": "vow_not_yet",
   "when": "A vow is not yet fulfilled",
   "text": "It's okay! You'll totally get it next time!"
  },
  {
   "id": "beacon",
   "when": "A beacon lights up",
   "text": "Look, look — a light came on! So pretty!"
  },
  {
   "id": "duplicate",
   "when": "Pulled again (duplicate)",
   "text": "Me again? Hehe, guess you really like me!"
  },
  {
   "id": "pity",
   "when": "Pull guarantee is close",
   "text": "Hm? The data's all fizzy… something big might be coming!"
  },
  {
   "id": "see_seren",
   "when": "Near Seren",
   "text": "Seren! You're sparkling again today — so bright!"
  },
  {
   "id": "see_ayaka",
   "when": "Near Ayaka",
   "text": "Ayaka, asleep again? …Let's sneak up and wake her!"
  },
  {
   "id": "see_mahesvara",
   "when": "Near Mahesvara",
   "text": "Mahesvara's a little scary… but he's actually kind, right?"
  },
  {
   "id": "see_kairo",
   "when": "Near Kairo (both from Hoshimura)",
   "text": "Kairo! Fellow Hoshimura kids — let's do our best together!"
  },
  {
   "id": "skill_1",
   "when": "Skill — Pixel Blink (proposed): glitch-teleport",
   "text": "Can't see me, right? Pixel Blink!"
  },
  {
   "id": "skill_2",
   "when": "Skill — Blaze Code (proposed): flame-sword slash",
   "text": "Burn! Blaze Code!"
  },
  {
   "id": "ultimate",
   "when": "Ultimate — Guardian Protocol (proposed): the mech's full attack",
   "text": "All systems unlocked! Guardian Protocol!"
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Great work, everyone~! Today's voyage was fun!"
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "See you! I'll be right here waiting!"
  }
 ],
 "lucien": [
  {
   "id": "reveal",
   "when": "Pull reveal",
   "text": "…So it was you who called me. On such a quiet night, too."
  },
  {
   "id": "reveal_2",
   "when": "Pull reveal, continued",
   "text": "Lucien Valmaire. People call me \"the Great Moon.\""
  },
  {
   "id": "vow_seal",
   "when": "Reveal: the three seals / the Vow close-up (whisper)",
   "text": "In the name of an old god… I bind my vow, here."
  },
  {
   "id": "sig_full",
   "when": "Hundredfold Chain (full chant)",
   "text": "Moon, hear my vow — lightning, link a hundredfold. Rain down — Hundredfold Chain!"
  },
  {
   "id": "sig_short",
   "when": "Hundredfold Chain (short call)",
   "text": "Hundredfold Chain."
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Oh? Do you need something from me?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "The mastermind? …I'm just a count who worries too much."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "That chant? It's not as easy as it looks, you know."
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "I can see ten years ahead. …Mostly."
  },
  {
   "id": "tap_5",
   "when": "Tapped (5th)",
   "text": "I'll protect your future. That's a promise."
  },
  {
   "id": "idle",
   "when": "Idle",
   "text": "The moon is lovely again tonight. …Let me rest a little."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Heh… you really never let me get bored."
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "You chose me? …Very well. I've already prepared a plan."
  },
  {
   "id": "walk_start",
   "when": "Starts walking",
   "text": "Shall we? The moonlight shows the way."
  },
  {
   "id": "fragments",
   "when": "Writing thoughts",
   "text": "Write what you think, just as it is. I won't tell anyone."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Three votes. Read the board, then choose where to place them."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your vow. …You may be proud."
  },
  {
   "id": "vow_not_yet",
   "when": "A vow not yet kept",
   "text": "No need to rush. The moon waits until it's full."
  },
  {
   "id": "beacon",
   "when": "A beacon is lit",
   "text": "A light has been kindled. This view is more than I foresaw."
  },
  {
   "id": "duplicate",
   "when": "Duplicate pull",
   "text": "Me again? …We must share quite a bond."
  },
  {
   "id": "pity",
   "when": "Pity is near",
   "text": "Can you feel it? A great current is heading this way."
  },
  {
   "id": "skill_1",
   "when": "Skill — Rampart of Stone",
   "text": "Earth, become a shield — Rampart of Stone."
  },
  {
   "id": "skill_2",
   "when": "Skill — Lunar Aegis",
   "text": "The moon's protection. Inside this, no one can touch you."
  },
  {
   "id": "ultimate",
   "when": "Ultimate — Thunder Sovereign",
   "text": "I offer this body to the lightning — Great Moon, shine on me! Thunder Sovereign!"
  },
  {
   "id": "see_mahesvara",
   "when": "Near Mahesvara (banner partner)",
   "text": "The one of the void. …I'm glad we're not enemies under the same moon."
  },
  {
   "id": "see_azrenth",
   "when": "Near Azrenth",
   "text": "Lord Demon King. …Even with lightning, you'd be hard work."
  },
  {
   "id": "secret",
   "when": "Random idle (the misunderstanding)",
   "text": "Everyone says Valmaire is terrifying. …When all I want is to protect you."
  },
  {
   "id": "misread",
   "when": "Random idle",
   "text": "Everyone thinks I have some deep plan… honestly, it's mostly instinct."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "A good voyage. Let's meet again on the next moonlit night."
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "Good night. The moon is watching over you."
  }
 ],
 "mahesvara": [
  {
   "id": "reveal",
   "when": "Pull reveal (base form)",
   "text": "…So you're the one who called me."
  },
  {
   "id": "reveal_2",
   "when": "Pull reveal, continued",
   "text": "Very well. I won't let you be bored."
  },
  {
   "id": "transform",
   "when": "Transformation to true form",
   "text": "Let me show you. This is my true form."
  },
  {
   "id": "true_reveal",
   "when": "True form appears",
   "text": "Destroy or restore — all of it answers to me."
  },
  {
   "id": "sig_destroy",
   "when": "Signature move — destroy",
   "text": "Vanish."
  },
  {
   "id": "sig_restore",
   "when": "Signature move — restore",
   "text": "…Return."
  },
  {
   "id": "sig_full",
   "when": "Signature move — full call",
   "text": "What exists, to nothing. What is lost, to form."
  },
  {
   "id": "nullify",
   "when": "Enemy magic nullified",
   "text": "You thought magic like that could reach me?"
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "What do you want?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "You bother with me? Strange taste."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "…Heh. You're interesting."
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "Touch me again and I'll take you apart. …That was a joke."
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "You chose me. A wise decision."
  },
  {
   "id": "idle",
   "when": "Idle",
   "text": "…Quiet. Not bad."
  },
  {
   "id": "walk_start",
   "when": "Starts walking",
   "text": "No need to hurry. The outcome won't change."
  },
  {
   "id": "fragments",
   "when": "Writing thoughts",
   "text": "Write what you really think. I can see through lies."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Three votes. …Spend them on what matters most."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your vow. …I'll acknowledge that."
  },
  {
   "id": "vow_not_yet",
   "when": "A vow is not yet fulfilled",
   "text": "Keep it next time. I only look at results."
  },
  {
   "id": "beacon",
   "when": "A beacon lights up",
   "text": "A light. …Restoring is harder than destroying."
  },
  {
   "id": "duplicate",
   "when": "Pulled again (duplicate)",
   "text": "Me again. …Lucky or unlucky, I wonder."
  },
  {
   "id": "pity",
   "when": "Pull guarantee is close",
   "text": "Do you feel it? The world is straining."
  },
  {
   "id": "see_ayaka",
   "when": "Near Ayaka",
   "text": "You stop it, I destroy it. …Efficient."
  },
  {
   "id": "see_seren",
   "when": "Near Seren",
   "text": "…Your light is one thing I don't feel like destroying."
  },
  {
   "id": "see_azrenth",
   "when": "Near Azrenth",
   "text": "A demon king. …I could entertain you."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "It's over. …I expect more next time."
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "Go. I'll be here."
  },
  {
   "id": "skill_1",
   "when": "Skill 1 (name TBD by Jay)",
   "text": "Disassemble."
  },
  {
   "id": "skill_2",
   "when": "Skill 2 (name TBD by Jay)",
   "text": "Spell — nullified."
  },
  {
   "id": "ultimate",
   "when": "Ultimate (name TBD by Jay)",
   "text": "Return to dust — the whole world with you."
  }
 ],
 "rook": [
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Yo. Need something?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Rules are made to be broken, you know."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "Don't rush. Even lightning picks where it strikes."
  },
  {
   "id": "idle",
   "when": "Random idle",
   "text": "Yawn… boring. Someone let me fire a shot."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Heh. Not bad."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Three votes? I don't miss."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "Kept your word, huh? Not bad at all."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "That's it for today. See ya, partner."
  }
 ],
 "seren": [
  {
   "id": "title_tap",
   "when": "Title screen, idle",
   "text": "Tap to start"
  },
  {
   "id": "welcome_first",
   "when": "First time, before nickname",
   "text": "Welcome to Lumara! What should I call you?"
  },
  {
   "id": "nickname_set",
   "when": "After typing a nickname",
   "text": "Nice to meet you, {nickname}!"
  },
  {
   "id": "intro_1",
   "when": "Intro card 1",
   "text": "The Dimming put out the beacons of Lumara."
  },
  {
   "id": "intro_2",
   "when": "Intro card 2",
   "text": "Every sprint, we reflect together. Your thoughts stay anonymous."
  },
  {
   "id": "intro_3",
   "when": "Intro card 3",
   "text": "Keep your vows, and the beacons return."
  },
  {
   "id": "arrive_sanctuary",
   "when": "First arrival",
   "text": "Welcome home, {nickname}. Your companion will find you soon."
  },
  {
   "id": "welcome_back_1",
   "when": "Returning (random)",
   "text": "Welcome back, {nickname}!"
  },
  {
   "id": "welcome_back_2",
   "when": "Returning (random)",
   "text": "You're here, {nickname}! It's brighter already."
  },
  {
   "id": "welcome_back_3",
   "when": "Returning (random)",
   "text": "Good to see you, {nickname}."
  },
  {
   "id": "tap_1",
   "when": "Tapping Seren (random)",
   "text": "Need something?"
  },
  {
   "id": "tap_2",
   "when": "Tapping Seren (random)",
   "text": "The view never gets old."
  },
  {
   "id": "tap_3",
   "when": "Tapping Seren (random)",
   "text": "Hehe — that tickles!"
  },
  {
   "id": "beacons_status",
   "when": "Tapping the beacon map",
   "text": "{lit} of 12 beacons shine again."
  },
  {
   "id": "voyage_starting",
   "when": "Warden starts a retro",
   "text": "A voyage is starting — join the party!"
  },
  {
   "id": "party_waiting",
   "when": "Party Gate, waiting",
   "text": "{here} of {total} Wardens here."
  },
  {
   "id": "party_ready",
   "when": "Everyone's here",
   "text": "Everyone's here!"
  },
  {
   "id": "stage_pull",
   "when": "Opening Pull",
   "text": "Pull your companion for this voyage!"
  },
  {
   "id": "stage_vows",
   "when": "Vow Review",
   "text": "Did we keep last voyage's vows?"
  },
  {
   "id": "stage_vows_none",
   "when": "Vow Review, first retro",
   "text": "Our first voyage! No vows to review yet."
  },
  {
   "id": "stage_fragments",
   "when": "Fragment Drop",
   "text": "Write your thoughts — they stay anonymous."
  },
  {
   "id": "stage_fragments_nudge",
   "when": "Fragment Drop, halfway",
   "text": "Even small thoughts matter."
  },
  {
   "id": "stage_vote",
   "when": "Vote",
   "text": "You have 3 votes. Stack them if you like!"
  },
  {
   "id": "stage_hall",
   "when": "Hall",
   "text": "Revealing thoughts — most voted first."
  },
  {
   "id": "stage_hall_next",
   "when": "Hall, next thought",
   "text": "Next thought…"
  },
  {
   "id": "stage_altar",
   "when": "Vow Altar",
   "text": "Turn today's talk into vows."
  },
  {
   "id": "stage_rewards",
   "when": "Rewards",
   "text": "Voyage complete! Starlight earned."
  },
  {
   "id": "stage_goodbye",
   "when": "Retro ends",
   "text": "See you next voyage, {nickname}!"
  },
  {
   "id": "pull_a",
   "when": "A-grade pull",
   "text": "A new companion!"
  },
  {
   "id": "pull_splus",
   "when": "S+ pull (gold)",
   "text": "Gold light — someone special!"
  },
  {
   "id": "pull_splusplus",
   "when": "S++ pull (prismatic)",
   "text": "A LEGEND HAS ANSWERED!"
  },
  {
   "id": "pull_seren",
   "when": "Someone pulls Seren",
   "text": "It's me! I'll take good care of you!"
  },
  {
   "id": "pull_duplicate",
   "when": "Duplicate",
   "text": "Duplicate — Stardust gained!"
  },
  {
   "id": "pity_close",
   "when": "Near guarantee",
   "text": "Something big is close…"
  },
  {
   "id": "vow_fulfilled",
   "when": "Vow marked fulfilled",
   "text": "Vow fulfilled — a beacon is relit!"
  },
  {
   "id": "vow_not_yet",
   "when": "Vow marked not yet",
   "text": "Not yet — that's okay."
  },
  {
   "id": "beacon_all_12",
   "when": "All 12 lit (rare)",
   "text": "All 12 beacons shine. Lumara lives again!"
  },
  {
   "id": "paused",
   "when": "Warden pauses",
   "text": "The voyage is paused."
  },
  {
   "id": "resumed",
   "when": "Resume",
   "text": "We're back!"
  },
  {
   "id": "skipped",
   "when": "Warden skips a stage",
   "text": "Moving on!"
  },
  {
   "id": "offline",
   "when": "Connection lost",
   "text": "Reconnecting…"
  },
  {
   "id": "skill_1",
   "when": "Skill — Dawn Slash",
   "text": "Blade of dawn — Dawn Slash!"
  },
  {
   "id": "skill_2",
   "when": "Skill — Guiding Light",
   "text": "It's okay — follow my light."
  },
  {
   "id": "ultimate",
   "when": "Ultimate — Dawnbreak",
   "text": "Darkness, give way to morning — Dawnbreak!"
  }
 ],
 "sollene": [
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Good evening. The moon is watching over you."
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "A quiet prayer steadies the sky."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "My crescent staff carries the light of home."
  },
  {
   "id": "idle",
   "when": "Random idle",
   "text": "The moonlight… it's so beautiful tonight."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Hehe… that makes me happy."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Listen to your heart, and choose."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "A promise kept. The moon rejoices too."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Thank you for today. Sweet dreams."
  }
 ],
 "suvara": [
  {
   "id": "reveal",
   "when": "Pull reveal",
   "text": "Did the light reach the edge of the horizon? …Yes. I have come."
  },
  {
   "id": "reveal_2",
   "when": "Pull reveal, continued",
   "text": "Suvara, Keeper of the Horizon. And this is my guardian dragon, Yulan."
  },
  {
   "id": "bond",
   "when": "Reveal: forehead to the dragon (soft)",
   "text": "Yulan… lend me your strength."
  },
  {
   "id": "sig_full",
   "when": "Sentinel's Descent (full call)",
   "text": "Come down from the heavens, other half of my soul — light the horizon! Sentinel's Descent!"
  },
  {
   "id": "sig_short",
   "when": "Sentinel's Descent (short call)",
   "text": "Sentinel's Descent."
  },
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Yes? Is there something you need?"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Yulan is shy with strangers. …Hehe, but it seems to like you."
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "I was taught that a ruler must not laugh. …That's our secret, all right?"
  },
  {
   "id": "tap_4",
   "when": "Tapped (4th)",
   "text": "This sword is heavy. But for protecting people, it is just the right weight."
  },
  {
   "id": "tap_5",
   "when": "Tapped (5th)",
   "text": "A light for your city, too. That is my duty."
  },
  {
   "id": "idle",
   "when": "Idle",
   "text": "…It's quiet. Yulan, you may sleep for a little while."
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Hehe… forgive me. I couldn't help it."
  },
  {
   "id": "select",
   "when": "Chosen as your character for the retro",
   "text": "You choose me? I'm honoured. I'll protect you, whatever it costs."
  },
  {
   "id": "walk_start",
   "when": "Starts walking",
   "text": "Let us go. Yulan, follow me."
  },
  {
   "id": "fragments",
   "when": "Writing thoughts",
   "text": "Honest words are what make a nation better. Please, write it as it is."
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Three votes. Use them with care, as the people's voice."
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your vow. …Splendid."
  },
  {
   "id": "vow_not_yet",
   "when": "A vow not yet kept",
   "text": "It's all right. The horizon won't run away. Step by step."
  },
  {
   "id": "beacon",
   "when": "A beacon is lit",
   "text": "A light has been kindled. Look, Yulan — isn't it beautiful?"
  },
  {
   "id": "duplicate",
   "when": "Duplicate pull",
   "text": "Me again…? Yulan is happy too."
  },
  {
   "id": "pity",
   "when": "Pity is near",
   "text": "Can you feel it? A light is approaching from beyond the horizon."
  },
  {
   "id": "skill_1",
   "when": "Skill — Crescent Horizon",
   "text": "Crescent moon, draw the horizon — Crescent Horizon!"
  },
  {
   "id": "skill_2",
   "when": "Skill — Lantern Ascent",
   "text": "Lanterns, rise. Light everyone's way."
  },
  {
   "id": "ultimate",
   "when": "Ultimate / big finisher",
   "text": "Yulan, now! Let us soar through the heavens together!"
  },
  {
   "id": "see_mahesvara",
   "when": "Near Mahesvara",
   "text": "You of the void… please never turn that power on the people."
  },
  {
   "id": "see_seren",
   "when": "Near Seren",
   "text": "Seren. Your light is warmer than my lanterns."
  },
  {
   "id": "see_lucien",
   "when": "Near Lucien",
   "text": "Count Valmaire. …Your schemes frighten me, just a little."
  },
  {
   "id": "duty",
   "when": "Random idle",
   "text": "Fulfilling my duty was my reason for living. …Now, it's a little different."
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "It was a good day. Let's protect tomorrow's horizon together, too."
  },
  {
   "id": "goodnight",
   "when": "Leaving the game",
   "text": "Good night. Yulan will guard your dreams."
  }
 ],
 "wren": [
  {
   "id": "greet",
   "when": "Tapped in the Sanctuary",
   "text": "Hey there! The wind brought me right to you!"
  },
  {
   "id": "tap_2",
   "when": "Tapped (2nd)",
   "text": "Where's our next adventure? I'll follow you anywhere!"
  },
  {
   "id": "tap_3",
   "when": "Tapped (3rd)",
   "text": "I never miss my target… probably!"
  },
  {
   "id": "idle",
   "when": "Random idle",
   "text": "The wind smells different… something good is coming!"
  },
  {
   "id": "laugh",
   "when": "Random idle",
   "text": "Ahaha! This is fun!"
  },
  {
   "id": "vote",
   "when": "Voting",
   "text": "Which one… okay, going with my gut!"
  },
  {
   "id": "vow",
   "when": "A vow is fulfilled",
   "text": "You kept your promise! Amazing!"
  },
  {
   "id": "retro_end",
   "when": "End of the retro",
   "text": "Good work! Let's ride the wind together again!"
  }
 ]
};
